# Generated by Django 4.2 on 2023-08-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
